### ISSUE TITLE
The new icon sets website's search bar is hard to click

### ISSUE THREAD

**Issue by KTibow** [iconify/website#22]
*This is the best repo I could find. It might be the wrong one, because i couldn't find one dedicated to icon-sets.iconify.design.*

In the "filter icons" bar, the search input is hard to click. You can't click on it from the edges of the search bar or by clicking on the icon (funnily the icon has a hover state even though you can't click on it to enter the text input), instead there's a very narrow area to click (<24px tall). I should be able to click anywhere in the search bar and focus the input.

**Comment by cyberalien** [comment]
Thanks for reporting!

Fixed and deployed.

**Comment by cyberalien** [comment]
Also fixing for other inputs, but that needs a bit more testing, so fix is not deployed yet

**Comment by KTibow** [comment]
All inputs I've tested still have this problem. What's going on?

**Comment by cyberalien** [comment]
I don't see any problems. Clicking container element focuses icon.

For some small inputs container is a bit inside of input, so clicking border area doesn't work, but its just few pixels difference.

**Comment by KTibow** [comment]
I would submit a PR that gives the intended behavior but I'm not sure where the source is.

**Comment by cyberalien** [comment]
Can you make a quick demo to show what exactly is not working? Screen recording or a screenshot with arrow pointing to location you are trying to click that doesn't work.

**Comment by cyberalien** [comment]
Gave you access to repo. Run `build` to build all packages (2 packages need building before it can be used: public/utils and private/utils, other packages don't require building). Website is in `iconify-ui/website`, run dev to run it in dev mode.
